# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0003_auto_20180928_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(default=True, to='galla.Categorys'),
        ),
    ]
