# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Category',
            field=models.ManyToManyField(to='galla.Categorys'),
        ),
        migrations.AddField(
            model_name='image',
            name='pud_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
