# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0004_auto_20180928_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
    ]
